services:
  mtg_db:
    container_name: mtg_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5431:5432
    volumes:
      - mtg_db:/var/lib/postgresql/data

volumes:
  mtg_db: {}
